VIA_ENABLE  = yes
VIAL_ENABLE = yes

BOOTMAGIC_ENABLE = no
TAP_DANCE_ENABLE = no

CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
SEND_STRING_ENABLE = yes
MOUSEKEY_ENABLE = yes

DEBOUNCE_TYPE = sym_defer_pr

